# Generated by Django 4.2.20 on 2025-04-19 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('invoice_email', models.EmailField(blank=True, max_length=254)),
                ('invoice_address', models.TextField(blank=True)),
                ('org_number', models.CharField(blank=True, max_length=20)),
                ('default_hour_rate', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='hour_rate',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='is_spot_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.customer'),
        ),
    ]
